# Generated by Django 4.2.2 on 2023-07-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
