# Generated by Django 4.2.2 on 2023-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_address', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('external_lines', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation', models.CharField(max_length=100)),
                ('station_nomenclature', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
