# Generated by Django 4.2.2 on 2023-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Othergroupings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='station_nomenclature',
            field=models.CharField(blank='True', max_length=100),
        ),
    ]
