# Generated by Django 4.2.2 on 2023-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infirmary_section', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('plc_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=100)),
                ('plc_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='systemCommunications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=100)),
                ('plc_number', models.CharField(max_length=100)),
            ],
        ),
    ]
