# Generated by Django 4.2.2 on 2023-08-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCentres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infirmary',
            options={'verbose_name_plural': 'Infirmaries'},
        ),
        migrations.AlterModelOptions(
            name='mis',
            options={'verbose_name_plural': 'MIS'},
        ),
        migrations.AlterModelOptions(
            name='systemcommunications',
            options={'verbose_name_plural': 'System Communications'},
        ),
    ]
